{
  "m_GameObject": {
    "m_FileID": 0,
    "m_PathID": 0
  },
  "m_Enabled": 1,
  "m_Script": {
    "m_FileID": 0,
    "m_PathID": -3078351595095444000
  },
  "m_Name": "945",
  "m_id": 945,
  "m_displayName": "CLAN QUEST - SCIENCE - OGREST - 04_Chapitre IV",
  "m_availability": 3,
  "m_i18nNameId": {
    "a": -1020425409,
    "b": -326805788,
    "c": -1200497253,
    "d": 1645583626,
    "e": 1308658877
  },
  "m_i18nDescriptionId": {
    "a": -1020425409,
    "b": -326805788,
    "c": -1200497253,
    "d": 1645583626,
    "e": -1246169815
  },
  "m_i18nDescriptionFinishedId": {
    "a": -1020425409,
    "b": -326805788,
    "c": -1200497253,
    "d": 1645583626,
    "e": 762717972
  },
  "values": {
    "type": "AchievementDefinition",
    "id": 945,
    "subAchievements": [
      1870
    ],
    "points": 10,
    "secret": false,
    "achievementType": 1,
    "rewards": [],
    "onSuccess": [],
    "precomputedData": {
      "type": "PrecomputedData",
      "dynamicValueReferences": [],
      "externalDynamicValueReferences": [],
      "hasEffects": false,
      "keywordReferences": [
        {
          "type": 1,
          "id": 4271
        }
      ]
    }
  },
  "name": {
    "fr": "Compléter le chapitre IV",
    "en": "",
    "es": "",
    "de": "",
    "pt": ""
  },
  "description": {
    "fr": "{Skin:4271} est perturbé. Est-il responsable des dangers qui rôdent autour de ses pivoines\\_? Sera-t-il à nouveau responsable d’un chaos dans le Monde des Douze\\_?",
    "en": "",
    "es": "",
    "de": "",
    "pt": ""
  },
  "descriptionFinished": {
    "fr": "{Skin:4271} a su faire face aux souvenirs qui le hantent, il reprend sa mission avec détermination. Autrefois, il a peut-être mis en danger le monde, mais aujourd’hui, il a une chance de se rattraper.",
    "en": "",
    "es": "",
    "de": "",
    "pt": ""
  }
}